name: sightai
channels:
  - conda-forge
  - pytorch
  - javascript
dependencies:
  - python=3.7
  - pytorch==1.5.1 
  - torchvision==0.6.1 
  - cudatoolkit=10.2
  - pandas==0.24.2 
  - numpy==1.16.3
  - matplotlib==2.2.3
  - joblib==0.13.2
  - pip
  - pip:
        - jupyterlab
        - Pillow==7.1.2
        - scikit_image==0.16.2
        - tqdm==4.43.0
        - easydict==1.9
        - opencv_python
        - logzero
        - DepthVisualizer
        - tensorboard 
        - albumentations
